version: '3'
services:
  xray:
    image: teddysun/xray
    container_name: xray
    restart: always
    network_mode: host
    volumes:
      - ./config.json:/etc/xray/config.json
    environment:
      - TZ=Asia/Shanghai
